
CREATE TABLE dados_analises(
    id INT PRIMARY KEY,
    diagnostico VARCHAR(5) NOT NULL,
    media_raio NUMERIC NOT NULL,
    media_textura NUMERIC NOT NULL,
    media_perimetro NUMERIC NOT NULL,
    media_area NUMERIC NOT NULL,
    media_suavidade NUMERIC NOT NULL,
    media_compactacao NUMERIC NOT NULL,
    media_concavidade NUMERIC NOT NULL,
    media_concavidade_pontos NUMERIC NOT NULL,
    media_simetria NUMERIC NOT NULL,
    media_dimensao_fractal NUMERIC NOT NULL,
    se_raio NUMERIC NOT NULL,
    se_textura NUMERIC NOT NULL,
    se_perimetro NUMERIC NOT NULL,
    se_area NUMERIC NOT NULL,
    se_suavidade NUMERIC NOT NULL,
    se_compactacao NUMERIC NOT NULL,
    se_concavidade NUMERIC NOT NULL,
    se_concavidade_pontos NUMERIC NOT NULL,
    se_simetria NUMERIC NOT NULL,
    se_dimensao_fractal NUMERIC NOT NULL,
    pior_raio NUMERIC NOT NULL,
    pior_textura NUMERIC NOT NULL,
    pior_perimetro NUMERIC NOT NULL,
    pior_area NUMERIC NOT NULL,
    pior_suavidade NUMERIC NOT NULL,
    pior_compactacao NUMERIC NOT NULL,
    pior_concavidade NUMERIC NOT NULL,
    pior_concavidade_pontos NUMERIC NOT NULL,
    pior_simetria NUMERIC NOT NULL,
    pior_dimensao_fractal NUMERIC NOT NULL
)